### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by Mateusz404** [NotRequiem/VMAware#208]
Hi! I've been using old version of VMAware beta version (it was compiling with no issues) and today I tried to update it to the 2.0 release. (Just dragged and dropped vmaware.hpp and overwritten the files). Unfortunately, the program doesn't compile anymore after doing so.

Errors are mostly from undeclared or not found identifiers

![Image](https://github.com/user-attachments/assets/683a0c6f-2752-4140-ab92-7a4abfa0333f)

The .hpp file is clean from the releases. My app is x32, target platform Windows.

**Comment by NotRequiem** [comment]
Hello, we just tested on MSVC with x32 and it compiled fine. Why is it saying "IsWIndowsVistaOrGreater is undefined" if we're not even using that function? Could you share your compiler settings with us?

I will add experimental fixes for the rest of the problems.

**Comment by NotRequiem** [comment]
Hi again @Mateusz404, I pushed a few changes to main, can you try to compile the library again?

**Comment by Mateusz404** [comment]
Your changes didn't fix my issue. However, the other developer from my team has removed these from the Release 2.0 version:
VM::THREADCOUNT
VM::VMWARE_EVENT_LOGS

And then it works, so we will just use the VMAware without those two. 
Something in our code base is probably incompatible with those, but I cannot share our code. 

I guess it can be closed if that's something specific to our project. Sorry for taking your time.

**Comment by NotRequiem** [comment]
In my changes, I did remove VM::VMWARE_EVENT_LOGS from being compiled for x86_32, as the technique might produce issues when running under 32 bits

As for VM::THREADCOUNT, the technique doesn't use any of the identifiers you have shown in the screenshot, so we can't really fix that without additional information

If possible, could you or your developer give more information about any other bugs that may have appeared during compilation? If not, we can proceed to close the issue if you want

Even before the latest push to the main branch, we didn't detect any issues with compilation for 32 bits:

![Image](https://github.com/user-attachments/assets/6bc742f4-74a4-492f-b2cc-d69252bccdb3)

**Comment by Mateusz404** [comment]
There was a huge list of errors, and I couldn't screen them all. For the second function, it was this error, I guess:

1>D:\repos\X\client\src\framework\vmaware\vmaware.hpp(2790,17): error C3861: 'GetLogicalProcessorInformationEx': identifier not found

**Comment by NotRequiem** [comment]
Very odd. `GetLogicalProcessorInformationEx` is included in the sysinfoapi.h, which is included in our library by importing <windows.h>. Plus, that API call is not even used in **VM::THREADCOUNT** or **VM::VMWARE_EVENT_LOGS**, it's only used in the `does_threadcount_mismatch` function, which in theory you're using and it compiled correctly according to you

You also shown an error related to the `IsWIndowsVistaOrGreater` function in the versionhelpers.h library, which we don't use

I know you mentioned you're compiling the latest source file without additional changes (by just dragging and dropping), but this makes no sense to me. Are you really making no changes to the library itself?

**Comment by Mateusz404** [comment]
No changes at all. I've recorded the whole process and the errors. 
Here it is: https://www.youtube.com/watch?v=olmeIfolTnk

**Comment by NotRequiem** [comment]
Same steps as you did, no issues: https://www.youtube.com/watch?v=-oH1s2wmqKM

This means that this is not a problem with the code itself, but with the difference between our project configurations.

Since all your errors are related to undeclared functions that are normally found in the Windows API headers, please try to check your project dependencies. Thanks for your patience and for reporting the issue :)

Is there anything else I can help you with?

**Comment by Mateusz404** [comment]
I'm good, thanks for your time and for looking into that. Have an excellent end of the weekend!
